### ISSUE TITLE
Suppress the progress bar

### ISSUE THREAD

**Issue by tkboyle** [Nanitor/log4fix#15]
Hi, the verbosity of the progress bar output is causing my output file to grow large very quickly.

Can there be a switch to resume the previous mode in 4.0.0 as this is be deployed remotely and I'm only interested in the output.txt file.

Like a --supress flag.

Within 32 seconds my own output file has 116k lines.

```
Scanning c:\
[0A[2K
[0A[2K
[0A[2K
[0A[2K
[0A[2K
[0A[2K
[0A[2K
[0A[2K
[0A[2K
[0A[2K
[0A[2K
[0A[2K
[0A[2K
Number of files scanned: 1000 
Number of files unable to access: 0
Number of .JAR found: 0
Number of .WAR found: 0
Number of .EAR found: 0
[0A[2K
[0A[2K
[0A[2K
[0A[2K
[0A[2K
[0A[2K
[0A[2K
```

**Comment by ahall** [comment]
Fixed in https://github.com/nanitor/log4fix/releases/tag/v4.2.0

**Comment by ahall** [comment]
The flag is --quiet btw.
