### ISSUE TITLE
Add functionality for file system scanning

### ISSUE THREAD

**Issue by SigursteinnBjarni** [Nanitor/log4fix#4]
Hi Nanitor!

Thank you for this contribution! 

It would be a great addition to the scanner if the default behavior would be to scan the entire file system on a targeted server. This could of course be an addition parameter as well

This would be beneficial to most users as it eliminates the need to know where .jar and .war are located.

**Comment by Skjaldbaka17** [comment]
Hi, thank you for this! 🐢

A scanning command has been added to master 🐢🐢🐢
