### ISSUE TITLE
Implement a scanning progress bar

### ISSUE THREAD

**Issue by ahall** [Nanitor/log4fix#9]
As scanning the filesystem takes a long time and outputting files we cannot access due to privilege issues is annoying, we want to implement a CLI progress bar that shows the following on the CLI:

Number of files scanned: 1 (This will update regularly)
Number of files unable to access: 1
Number of JAR/WAR/EAR found: 1

**Comment by Skjaldbaka17** [comment]
🐢

**Comment by tkboyle** [comment]
Hi, the verbosity of the progress bar output is causing my output file to grow large very quickly.

Can there be a switch to resume the previous mode in 4.0.0 as this is be deployed remotely and I'm only interested in the output.txt file. 

Like a --quiet flag.
